training:
  learning_rate: 0.0001
  batch_size: 8
  epochs: 10

testing:
  model_path: "unet_carvana.pth"
  batch_size: 8
  epochs: 10

dataset:
  image_size: [256, 256]  
  augmentation: False      

